### ISSUE TITLE
it aint working

### ISSUE THREAD

**Issue by wasomereal** [wafflethings/WafflesWeapons#1]
i put it in my mod folder and it doesnt work and nothin happens

**Comment by wasomereal** [comment]
ok fr what the fuck why do you want me to edit and runa  bat file this shit aint even working

**Comment by wasomereal** [comment]
WHAT THE FUCK IS EXTRAALTS THAT SHIT IS NOT REAL THAT FILE IS FUCKIGN NON EXISTENT WHAT THE FUCK DO YOU MEAN

**Comment by wasomereal** [comment]
update i installed itusing the weird ass bitcoin miner overwolf shit and that worked just fine :steamhappy:

**Comment by PaolottoGames** [comment]
what

**Comment by PaolottoGames** [comment]
how did you make it work?
