### ISSUE TITLE
S.L.F. Striker Rocket Launcher can be charged by hitting rockets manually + Charge not incrementing unless S.L.F. is pulled out at least once

### ISSUE THREAD

**Issue by UntotenTheo** [wafflethings/WafflesWeapons#12]
Really long title but I don't know if i want to make 2 different issues for the same weapon

1. Shooting any Rocket with a Hitscan weapon will increment the charge of the S.L.F. Striker Alternate Fire

2. The S.L.F. Striker Alternate Fire will not charge unless the weapon has been pulled out at least once, firing is **not** necessary, hitting an enemy is **not** necessary, it only needs to be pulled out once for it to begin charging.

Once it has been pulled out, all Rocket Launchers will then contribute to the charge on direct hits or when a Rocket is shot using a hitscan weapon.

**Comment by wafflethings** [comment]
oops, ill fix this
