### ISSUE TITLE
Earthshatter Arm Charge can be stored

### ISSUE THREAD

**Issue by UntotenTheo** [wafflethings/WafflesWeapons#17]
Charging the Earthshatter Arm then swapping to a different arm allows you to instantly use the Earthshatters attack by tapping the Punch Key once swapped back to said arm.

While I don't use the Arm at all, I'm not 100% sure if this should be removed as honestly it seems like an interesting enough bug that may have some tactical applications.
Regardless, I believe this is a bug, so I've come here to inform you of such.

**Comment by wafflethings** [comment]
i think it's fun so im keeping it :3
