### ISSUE TITLE
Weapons don't have shaders compiled for OpenGLCore

### ISSUE THREAD

**Issue by MechaXYZ** [wafflethings/WafflesWeapons#21]
pretty sure this is the same thing as https://github.com/Hydraxous/UltraFunGuns/issues/41
![image](https://github.com/wafflethings/WafflesWeapons/assets/93439705/0e9fd764-b096-4961-b245-fee2125164b3)

**Comment by wafflethings** [comment]
they have for a while i just havent updated since then
