### ISSUE TITLE
Mod not working(Setup)

### ISSUE THREAD

**Issue by PaolottoGames** [wafflethings/WafflesWeapons#4]
I downloaded the zip file from the github, put it in bepinex/plugins but it didnt work.

**Comment by PaolottoGames** [comment]
and using the setup doesnt work (even by editing it)

**Comment by MaximKhannanov** [comment]
Same issue here

**Comment by SamuelBucher** [comment]
Same issue here.

**Comment by SamuelBucher** [comment]
Probably because there is a file called SETUP (edit first).bat in the mod folder, which needs to be run to set the mod up. But for some reason, no matter what paths I write in it, they are always considered incorrect.

**Comment by wafflethings** [comment]
you downloaded the source code 💀

**Comment by PaolottoGames** [comment]
its not the download that doesnt work, its the mod itself, there is no instructions of how setting it up (or it the mod doesnt work)

**Comment by PaolottoGames** [comment]
i do have UMM but if thats the case fix it please

**Comment by PaolottoGames** [comment]
but where is the download then?
