### ISSUE TITLE
Suggestion on the Earthshatter

### ISSUE THREAD

**Issue by YeImdedInlife** [wafflethings/WafflesWeapons#5]
Two suggestion actually:

**1.** I think the Earthshatter should work like the Knuckleblaster, (suggesting this cuz you cant grab stuff with the earthshatter)  but instead of the shockwave, the well dash you make; for example.

When I punch normally nothing happens, the normal punch, no parries, no nothing. **BUT** when the charging anim plays, you can use it's abilty by releasing the punch key.

Also you can put this as a setting if u want to.

**2.** Parrying enemy projectiles when using it's ability for idk more fun i guess

**(sorry if bad english)**

**Comment by wafflethings** [comment]
i will probably make it punch but parrying is OP
