### ISSUE TITLE
Various Enhancements/Suggestions

### ISSUE THREAD

**Issue by Mr-Foxtrot** [wafflethings/WafflesWeapons#6]
I love this mod, been waiting for it's release for a while and now that it's out I wanted to give my thoughts/suggestions on ways to improve it.

Fan Fire: Perfect, i've got no issues or suggestions to improve this. It's a great variant.

Malevolent: Normal version is perfect, though I feel the Slab version has 1 issue. You can't really "railcoin" with it, as the explosion is only on the first pierce, and not subsequent pierces to a target.

Demolitionist: Explosive should bounce off of Maurice, instead of just exploding immediately. The projectile should also "tumble" as it falls through the air, instead of just being static in it's rotation. Shots from other weapons that impact mines on the ground should detonate them as well.

Airblast: Normal is great, Alternate needs a bit more knockback. Also the saws from the alternate have strange physics, where the saws will bounce once then start slowly tumbling like it's got 0 gravity and dissappear shortly after. I also can't seem to tell if magnets can pick up the alternate saws?

Virtuous: Damage output is pretty powerful, but needs a wider blast radius as a majority of enemies will just move outside of it due to how small it is. Either increase the radius by a bit by default OR make the radius increase in size with each hit enemy.

S.L.F. Striker: Overall really cool, though I feel the speed of the alt-fire rocket should be faster in it's movement speed.

Earthshatter: Amazing custom arm, with only 2 suggestions. 1. The arm is REALLY far away from the camera when browsing the shop/interacting with terminals compared to the other arms. When you switch between the feedbacker/knuckleblaster, then to the Earthshatter, they are much closer to the camera than the earthershatter. 2. Why doesn't the earthshatter have a normal quick punch? I was doing a generic test with Minos and went to P-1, and realized I literally couldn't pick up the torch at the beginning (unless I switched to a different arm or used the whiplash) because there is no normal punch, only the charge. I suggest it should work like the knuckleblaster, where tapping the punch key will just do a normal punch but holding it will charge it.

**Comment by wafflethings** [comment]
almost all of these have either been fixed or should be fixed next update
