### ISSUE TITLE
Mod still not working

### ISSUE THREAD

**Issue by PaolottoGames** [wafflethings/WafflesWeapons#7]
I downloaded it and put it in Bepinex/Plugins but doesnt work, my last issue got closed but the problem is not solved.

![image](https://user-images.githubusercontent.com/113106793/226928135-8eb366cf-5f7d-42cf-90ef-21c75c5628bd.png)

https://user-images.githubusercontent.com/113106793/226930791-c20eeef3-8745-4fd2-8b7f-1e5daf636c8d.mp4

I only have UMM in Bepinex/Plugins

**Comment by PaolottoGames** [comment]
there is no relese nor tags soo what do i do?

**Comment by PaolottoGames** [comment]
Found out why, how you set it up its weird

**Comment by yeetus1000** [comment]
> Found out why, how you set it up its weird

how do you even set it up im confused
