### ISSUE TITLE
If you are having trouble with setting up the mod [Not an issue but dont close for new comers]

### ISSUE THREAD

**Issue by PaolottoGames** [wafflethings/WafflesWeapons#8]
--[You need to download both [ThunderStore](https://thunderstore.io/c/ultrakill/p/Waff1e/WafflesWeapons/) and [Github Source code](https://github.com/wafflethings/WafflesWeapons)]--

*for downloading on Thunder store you can just click "Manual Download" and export it in BepInEx/plugins.

*for downloading the source code on Github you click on "Code" and then "Download ZIP" and export in BepInEx/plugins

I dont know how or why but it will work (it worked to me).

**Comment by PaolottoGames** [comment]
The creator made a [video](https://youtu.be/rhMKhFNtiNA) of how to install it, but if you don't want to install the mod manager and other stuff to just install the mod, follow the insteuctions above

**Comment by wafflethings** [comment]
you shouldnt be downloading the source code to run it lol
