### ISSUE TITLE
the problem with the weapon menu

### ISSUE THREAD

**Issue by helldel722** [wafflethings/WafflesWeapons#9]
Damn waffle, I have a problem,
for some reason I don't switch pages with guns,
here's a button to switch, but it doesn't respond,
 I hope you will fix this problem :)
(sorry, my English is bad)

**Comment by PaolottoGames** [comment]
I made a page telling how to set it up, go look at that.

**Comment by helldel722** [comment]
I have already looked through all the pages on github related to this issue.
can you tell me on which points to describe everything so that there are fewer questions?

**Comment by PaolottoGames** [comment]
Look at the page i made "If you are having trouble setting up the mod"
